### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by daviwil** [SeeminglyScience/PSESHelperLibrary#8]
Sorry to abuse an issue for this :)

This is really cool, thanks for putting it together.  I'm just about to start adding some more APIs to $psEditor to get it fleshed out for the upcoming 1.0 release.  I saw the one bug you filed already, but definitely let me know of anything else you think would be cool or helpful in the API!

**Comment by SeeminglyScience** [comment]
Thank you so much! That really means a lot.

I'll definitely get some feature requests filed soon :)

And thanks for all your hard work, VSCode has been an absolute pleasure to use!

**Comment by TylerLeonhardt** [comment]
where it all began.... 😮
